apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  labels:
    app: petclinic
spec:
  selector:
    matchLabels:
      app: petclinic
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: petclinic
        tier: frontend
    spec:
      containers:
        - image: arey/springboot-petclinic
          name: petclinic
          resources:
            limits:
              memory: "512M"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: mysql
          ports:
            - containerPort: 8080
              name: petclinic
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
      tolerations:
          - effect: NoExecute
            key: node.kubernetes.io/not-ready
            operator: Exists
            tolerationSeconds: 30
          - effect: NoExecute
            key: node.kubernetes.io/unreachable
            operator: Exists
            tolerationSeconds: 30
